### ISSUE TITLE
Can't create a non-final subclass

### ISSUE THREAD

**Issue by melix99** [jf2048/gobject#14]
When I try to create a non-final subclass, like `#[gobject::class(extends(ObjAbstract))]`, it errors out: `the trait 'ObjAbstractImpl' is not implemented for '____Object'`. Am I missing something?

**Comment by jf2048** [comment]
Right now you always need to implement the trait for the subclass even if it is empty:

```rust
impl ObjAbstractImpl for MyObject {}
```

There is not really a good way to fill that in automatically, I guess it could try to not generate that trait if there are no virtual methods

**Comment by melix99** [comment]
Right, I forgot to mention that I added that trait. To replicate what I'm doing you can just delete the `final` attribute of the `Implementor` gobject in [this test case](https://github.com/jf2048/gobject/blob/main/tests/virtual_methods.rs).

**Comment by jf2048** [comment]
Ok, this a is a bit obtuse but you can do it. When making a non-final subclass you need to add `parent_trait`:

```rust
#[gobject::class(extends(ObjAbstract), parent_trait = "super::ObjAbstractImpl")]
```

This has to be done because it is not really possible to always infer the parent trait. The trait path is also scoped wrong and I can't think of a good way to fix that, but you could consider it a bug

**Comment by jf2048** [comment]
It's worth a shot to try to move `IsImplementable` and `IsSubclassable` outside the module, that should fix the scoping issue

**Comment by melix99** [comment]
> When making a non-final subclass you need to add parent_trait

This works, but I noticed that as soon as I add a virtual method to it, it starts complaining: 

```
38 | #[gobject::class(extends(ObjAbstract), parent_trait = "super::ObjAbstractImpl")]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `gobject::glib::Object::ObjectSubclassIs`
```

Not sure if this is related to this issue.

**Comment by jf2048** [comment]
That one was a typo, should be fixed now

**Comment by melix99** [comment]
It seems fixed when subclassing from custom gobjects, but if I subclass from a gtk::Widget, it's still broken:

```rust
#[gobject::class(extends(gtk::Widget), parent_trait = "gtk::subclass::prelude::WidgetImpl")]
mod obj {
    #[derive(Default)]
    pub struct CustomWidget {}
    impl CustomWidget {
        // Remove this method to unbreak
        #[virt]
        fn virtual_method(&self) {
            println!("virtual");
        }
    }
    impl gtk::subclass::prelude::WidgetImpl for CustomWidget {}
}
```

```
error[E0277]: the trait bound `gtk4::Widget: ObjectSubclassIs` is not satisfied
  --> ...
   |
   | #[gobject::class(extends(gtk::Widget), parent_trait = "gtk::subclass::prelude::WidgetImpl")]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `ObjectSubclassIs` is not implemented for `gtk4::Widget`
```
